### ISSUE TITLE
运行4h报错清理截图资源失败

### ISSUE THREAD

**Issue by James0324001** [lazydog28/mc_auto_boss#114]
2024-06-21 18:03:56 战斗次数：429 吸收次数：193 当前页面：推荐等级
2024-06-21 18:04:01 战斗次数：429 吸收次数：193 当前页面：开启挑战
2024-06-21 18:06:39 战斗次数：429 吸收次数：193 清理截图资源失败: DeleteDC failedProcess task:
Traceback (most recent call last):
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\tool\mc_auto_boss-gpu-new\mc_auto_boss-gpu\background\main.py", line 32, in run
    img = screenshot()
  File "D:\tool\mc_auto_boss-gpu-new\mc_auto_boss-gpu\background\utils.py", line 254, in screenshot
    hwndDC = win32gui.GetWindowDC(hwnd)  # 获取窗口设备上下文（DC）
pywintypes.error: (1400, 'GetWindowDC', '无效的窗口句柄。')

**Comment by lazydog28** [comment]
游戏窗口找不到了，是游戏闪退了？

**Comment by James0324001** [comment]
估计是，我遇到两次了。

**Comment by lazydog28** [comment]
那没啥办法

**Comment by lazydog28** [comment]
装个清理内存的插件 定时清理内存
