### ISSUE TITLE
你好请问我运行出现这种情况是怎么回事

### ISSUE THREAD

**Issue by sakuraletters** [lazydog28/mc_auto_boss#12]
File "<string>", line 1, in <module>
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\wdnsc\Desktop\国境以南、\mc_auto_boss-master\background\main.py", line 5, in <module>
    from utils import screenshot, ocr, search_text
  File "C:\Users\wdnsc\Desktop\国境以南、\mc_auto_boss-master\background\utils.py", line 180, in <module>
    ocrIns = PaddleOCR(
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py", line 616, in __init__
    super().__init__(params)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\utility.py", line 280, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\wdnsc\Desktop\国境以南、\mc_auto_boss-master\models/det/ch/ch_PP-OCRv4_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2578)

**Comment by lazydog28** [comment]
用最新的代码，你的用户名是中文导致加载模型失败

**Comment by sakuraletters** [comment]
好的谢谢

**Comment by lazydog28** [comment]
> 好的谢谢


项目路径也不能有中文

**Comment by sakuraletters** [comment]
现在我改路径之后出现了其他的情况
Traceback (most recent call last):
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Apps\mc_auto_boss-master\background\main.py", line 159, in run
    func()
  File "C:\Apps\mc_auto_boss-master\background\main.py", line 31, in boss_task
    ocrResults = ocr(img)
  File "C:\Apps\mc_auto_boss-master\background\utils.py", line 77, in ocr
    results = ocrIns.ocr(img, cls=False)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\paddleocr.py", line 668, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "C:\Users\wdnsc\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\inference\wrapper.py", line 52, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)

**Comment by sakuraletters** [comment]
![Uploading {F8D066F0-D388-480F-927F-65A012FE6A7A}.png…]()

**Comment by sakuraletters** [comment]
![{F8D066F0-D388-480F-927F-65A012FE6A7A}](https://github.com/lazydog28/mc_auto_boss/assets/171579904/cd239221-b0ad-46e5-beec-fa0e601784b0)

**Comment by sakuraletters** [comment]
ok解决了 把requirements.txt重装了下，可能是我前面操作弄得有什么冲突了
