### ISSUE TITLE
启动出现问题

### ISSUE THREAD

**Issue by Toki1020** [lazydog28/mc_auto_boss#150]
找了一圈好像没有人跟我有一样问题
(mc) PS C:\Users\limbe\Downloads\mc_auto_boss-gpu> python background/main.py
Traceback (most recent call last):
  File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\main.py", line 2, in <module>
    import init  # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!!
  File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\init.py", line 10, in <module>
    from status import logger
  File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\status.py", line 10, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'

**Comment by Toki1020** [comment]
> 找了一圈好像没有人跟我有一样问题 (mc) PS C:\Users\limbe\Downloads\mc_auto_boss-gpu> python background/main.py Traceback (most recent call last): File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\main.py", line 2, in import init # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!! File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\init.py", line 10, in from status import logger File "C:\Users\limbe\Downloads\mc_auto_boss-gpu\background\status.py", line 10, in from pydantic import BaseModel, Field ModuleNotFoundError: No module named 'pydantic'

要自行安装这些
```
pip install pydantic
pip install pyyaml
pip install pynput
pip install pywin32
```
