### ISSUE TITLE
国际版鸣潮注册表项目名称不符合，会导致报错

### ISSUE THREAD

**Issue by PrinceZW96** [lazydog28/mc_auto_boss#151]
1.1 版本 国际服鸣潮 注册表项目位于：
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\KRInstall Wuthering Waves Overseas

目前config.py 只会检查        
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\KRInstall Wuthering Waves

异常处理顺序有些问题，直接运行会报错：
Traceback (most recent call last):
  File "D:\mc_auto_boss\background\main.py", line 2, in <module>
    import init  # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!!
    ^^^^^^^^^^^
  File "D:\mc_auto_boss\background\init.py", line 10, in <module>
    from status import logger
  File "D:\mc_auto_boss\background\status.py", line 11, in <module>
    from config import config
  File "D:\mc_auto_boss\background\config.py", line 96, in <module>
    config = Config(**yaml.safe_load(f))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mc_auto_boss\background\config.py", line 61, in __init__
    self.AppPath = get_wuthering_waves_path()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mc_auto_boss\background\config.py", line 88, in get_wuthering_waves_path
    key.Close()
    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Close'

**Comment by Toki1020** [comment]
感谢！后面加上Overseas就能运行了

**Comment by lazydog28** [comment]
已经合并PR
