### ISSUE TITLE
关于a卡使用

### ISSUE THREAD

**Issue by KokonaShiki** [lazydog28/mc_auto_boss#256]
搭建gpu环境需要用到cuda，目前我的显卡是a卡，有什么替代的方法吗....

**Comment by ArcS17** [comment]
在安装飞桨paddlepaddle的过程中选择CPU版本，后续安装依赖导入requirements_cpu.txt

**Comment by KokonaShiki** [comment]
抱歉我没有注意到飞桨的cpu版本部分且没有仔细阅读readme，目前已经调试完毕，多谢开发者

**Comment by suwenjie-e5** [comment]
) PS D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu> python .\background\main.py
Traceback (most recent call last):
  File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\main.py", line 3, in <module>
    import init  # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!!
  File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\init.py", line 10, in <module>
    from status import logger
  File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\status.py", line 11, in <module>
    from config import config
  File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 138, in <module>
    config = Config(**yaml.safe_load(f))
  File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 80, in __init__
    super().__init__(**data)
  File "D:\minnicoda\envs\mc\lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
TargetBoss
  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type
这是为什么，安装的cpu环境也不行吗
