### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by suwenjie-e5** [lazydog28/mc_auto_boss#257]
笔记本核显a卡能用吗

**Comment by ArcS17** [comment]
参考 #256

**Comment by KokonaShiki** [comment]
iu+a卡可以使用，理论上笔记本也能使用，不过运算全部在cpu完成可能需要注意散热，安装过程飞桨命令记得选cpu版本 #256 即可

**Comment by suwenjie-e5** [comment]
PS D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu> python .\background\main.py
Traceback (most recent call last):
File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\main.py", line 3, in
import init # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!!
File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\init.py", line 10, in
from status import logger
File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\status.py", line 11, in
from config import config
File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 138, in
config = Config(**yaml.safe_load(f))
File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 80, in init
super().init(**data)
File "D:\minnicoda\envs\mc\lib\site-packages\pydantic\main.py", line 193, in init
self.pydantic_validator.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
TargetBoss
Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.8/v/list_type
安装的是cpu版本，

**Comment by lazydog28** [comment]
配置文件有问题

> PS D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu> python .\background\main.py Traceback (most recent call last): File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\main.py", line 3, in import init # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!! File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\init.py", line 10, in from status import logger File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\status.py", line 11, in from config import config File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 138, in config = Config(**yaml.safe_load(f)) File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 80, in init super().init(**data) File "D:\minnicoda\envs\mc\lib\site-packages\pydantic\main.py", line 193, in init self.pydantic_validator.validate_python(data, self_instance=self) pydantic_core._pydantic_core.ValidationError: 1 validation error for Config TargetBoss Input should be a valid list [type=list_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/list_type 安装的是cpu版本，

**Comment by suwenjie-e5** [comment]
> 配置文件有问题
> 
> > PS D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu> python .\background\main.py Traceback (most recent call last): File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\main.py", line 3, in import init # !!此导入删除会导致不会将游戏移动到左上角以及提示当前分辨率!! File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\init.py", line 10, in from status import logger File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\status.py", line 11, in from config import config File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 138, in config = Config(**yaml.safe_load(f)) File "D:\mcjiaoben\mc_auto_boss-gpu\mc_auto_boss-gpu\background\config.py", line 80, in init super().init(**data) File "D:\minnicoda\envs\mc\lib\site-packages\pydantic\main.py", line 193, in init self.pydantic_validator.validate_python(data, self_instance=self) pydantic_core._pydantic_core.ValidationError: 1 validation error for Config TargetBoss Input should be a valid list [type=list_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.8/v/list_type 安装的是cpu版本，

怎么改，

**Comment by lazydog28** [comment]
> Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]

你配置文件截图呢

**Comment by suwenjie-e5** [comment]
![QQ20240712-224730](https://github.com/user-attachments/assets/a9e17f38-4bfc-4daf-8905-46a50e3ac7e6)
![QQ20240712-224757](https://github.com/user-attachments/assets/1c356137-ac48-42bd-9300-4bed6e8c6848)

**Comment by suwenjie-e5** [comment]
找到原因乐，我配制文件里最后角前面多一个井号，我以为是忘记加了，结果好像改错了

**Comment by suwenjie-e5** [comment]
外行人有点想当然了

**Comment by suwenjie-e5** [comment]
![QQ_1720797140014](https://github.com/user-attachments/assets/540a27f4-7afe-4c8b-9e06-1cf9fdbb4c0d)
我以为是你们忘记加了，原来我才是小丑

**Comment by yeming1999** [comment]
可以，我就是笔记本，不过集成显卡比较卡，建议换成独显
