### ISSUE TITLE
内存管理存在问题？

### ISSUE THREAD

**Issue by 341816041** [lazydog28/mc_auto_boss#26]
![ee78f8e499bcbd3dcfd96b66fde6fd79](https://github.com/lazydog28/mc_auto_boss/assets/100549608/9873cdb7-cb0d-42b4-a732-09e048250556)
![77242e2a00f12acdee0773f5888a32b8](https://github.com/lazydog28/mc_auto_boss/assets/100549608/4a41d890-0e56-497b-9861-fec47a36eeb2)

**Comment by 341816041** [comment]
2024-06-05 07:37:54 当前角色状态：Status.idle 前进Process task:
Traceback (most recent call last):
  File "C:\Users\mya\.conda\envs\mc\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\mya\.conda\envs\mc\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\mcjb\mc_auto_boss\background\main.py", line 139, in run
    func()
  File "F:\mcjb\mc_auto_boss\background\main.py", line 73, in battle_task    ocrResults = ocr(img)
  File "F:\mcjb\mc_auto_boss\background\utils.py", line 76, in ocr
    results = ocrIns.ocr(img, cls=False)
  File "C:\Users\mya\.conda\envs\mc\lib\site-packages\paddleocr\paddleocr.py", line 668, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Users\mya\.conda\envs\mc\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 105, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "C:\Users\mya\.conda\envs\mc\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 619, in __call__
    output = output_tensor.copy_to_cpu()
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 33.2 MiB for an array with shape (5, 263, 6625) and data type float32

这里手动按了下f12 正常退出
2024-06-05 07:38:44 当前角色状态：Status.idle 退出脚本结束运行
