### ISSUE TITLE
关于F8声骸锁定的BUG

### ISSUE THREAD

**Issue by yeming1999** [lazydog28/mc_auto_boss#288]
在识别到哀声鸷时，报错"Traceback (most recent call last):
  File "D:\Game\miniconda3\envs\myenv\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Game\miniconda3\envs\myenv\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Game\miniconda3\mc_auto_boss-gpu\background\main.py", line 179, in run
    task(img, result)
  File "D:\Game\miniconda3\mc_auto_boss-gpu\background\schema.py", line 286, in __call__
    page.action(page.matchPositions)
  File "D:\Game\miniconda3\mc_auto_boss-gpu\background\task\pages\echo_bag_lock.py", line 22, in echo_bag
    if echo_bag_lock() is False:
       ^^^^^^^^^^^^^^^
  File "D:\Game\miniconda3\mc_auto_boss-gpu\background\utils.py", line 1223, in echo_bag_lock
    len(cost_config_dict.get(this_echo_cost_key)) == 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()"

**Comment by yeming1999** [comment]
我的配置文件是这样的：
# 请配置你所需要的套装、Cost、以及其对应属性
EchoLockConfig:
  浮星祛暗:
    1COST: ["攻击"]
    3COST: ["共鸣效率", "衍射伤害加成", "攻击"]
    4COST: ["暴击"]

**Comment by yeming1999** [comment]
修改了，background/utils.py  1099行的echo_bag_lock 函数中可能导致 NoneType 错误的问题
def echo_bag_lock():
    is_echo_ebug = False  # Debug打印开关
    adapts()
    """
    声骸锁定
    param is_echo_ebug 用于声骸识别过程Debug
    """
    # 开始执行判断
    if not config.EchoLock:
        logger("未启用该功能，请在config.yaml中更改EchoLock配置", "WARN")
        return False
    info.echoNumber += 1
    this_echo_row = info.echoNumber // 6 + 1
    this_echo_col = info.echoNumber % 6
    if this_echo_col == 0:
        this_echo_col = 6
        this_echo_row -= 1
    if info.echoNumber == 1:
        logger(
            "检测到声骸背包画面，3秒后将开始执行锁定程序，过程中请不要将鼠标移到游戏内。",
            "DEBUG",
        )
        logger(
            "tips:此功能需要关闭声骸详细描述(即在角色声骸装备处显示详情，在背包内显示简介)",
            "WARN",
        )
        logger(
            "步骤:点击键盘【C键】打开共鸣者，点击声骸，点击任意声骸，点击右上角简述将开关拨向左边",
            "WARN",
        )
        logger(
            "请使用已适配分辨率：\n  1920*1080分辨率1.0缩放\n  1600*900分辨率1.0缩放\n  1368*768分辨率1.0缩放\n  1280*720分辨率1.5缩放\n  1280*720分辨率1.0缩放",
            "WARN",
        )
        time.sleep(3)
        # 切换到时间顺序(倒序)
        logger("切换为时间倒序")
        random_click(400, 990)  # 调整点击位置以适配窗口模式下的1920*1080分辨率(ArcS17)
        time.sleep(1)
        random_click(400, 860)
        time.sleep(0.5)
        random_click(718, 23)
        time.sleep(0.5)
    if config.EchoDebugMode:
        logger(
            f"当前为第{this_echo_row}排，第{this_echo_col}个声骸 (总第{info.echoNumber}个)",
            "DEBUG",
        )
    echo_start_position = [285, 205]  # 第一个声骸的坐标
    echo_spacing = [165, 205]  # 两个声骸间的间距
    this_echo_x_position = (this_echo_col - 1) * echo_spacing[0] + echo_start_position[
        0
    ]  # 当前需要判断的声骸x坐标
    random_click(this_echo_x_position, echo_start_position[1])  # 选择当前声骸
    time.sleep(0.3)

    # 判断声骸是否为金色品质，如果不是则返回
    check_point = (1704, 393)
    if not contrast_colors(check_point, (255, 255, 255)):
        if config.EchoDebugMode:
            logger("当前声骸不是金色声骸，下一个", "DEBUG")
        echo_next_row(info.echoNumber)
        return True
    # 判断当前声骸是否未锁定
    img = screenshot()
    coordinate_unlock = find_pic(
        1700, 270, 1850, 395, f"声骸未锁定{info.adaptsResolution}.png", 0.98, img, False
    )
    # 先检测未锁定，再检测锁定，更快
    if coordinate_unlock:
        this_echo_lock = False
        info.echoIsLockQuantity = 0
        if config.EchoDebugMode:
            logger("当前声骸未锁定", "DEBUG")
    # 是否为锁定
    elif find_pic(
        1700, 270, 1850, 395, f"声骸锁定{info.adaptsResolution}.png", 0.98, img, False
    ):
        info.echoIsLockQuantity += 1
        if config.EchoDebugMode:
            logger("当前声骸已锁定", "DEBUG")
        if info.echoIsLockQuantity > config.EchoMaxContinuousLockQuantity:
            logger(
                f"连续检出已锁定声骸{info.echoIsLockQuantity}个，超出设定值，结束",
                "DEBUG",
            )
            logger(
                f"本次总共检查{info.echoNumber}个声骸，有{info.inSpecEchoQuantity}符合条件并锁定！！"
            )
            return False
        echo_next_row(info.echoNumber)
        return True
    else:
        logger("未检测到当前声骸锁定状况", "WARN")
        return False

    # 识别声骸Cost
    this_echo_cost = None
    # 先检测cost 4
    if find_pic(
        1690, 200, 1830, 240, f"COST4{info.adaptsResolution}.png", 0.98, img, False
    ):
        this_echo_cost = "4"
    elif find_pic(
        1690, 200, 1830, 240, f"COST1{info.adaptsResolution}.png", 0.98, img, False
    ):
        this_echo_cost = "1"
    elif find_pic(
        1690, 200, 1830, 240, f"COST3{info.adaptsResolution}.png", 0.98, img, False
    ):
        this_echo_cost = "3"

    if this_echo_cost is None:
        logger("未能识别到Cost", "ERROR")
        return False
    if config.EchoDebugMode:
        logger(f"当前声骸Cost为{this_echo_cost}", "DEBUG")

    this_echo_cost_key = this_echo_cost + "COST"

    # 当配置文件每个套装的这个cost值需要的词条一条也没写，即都不需要，直接跳过，不检测主词条
    this_echo_cost_not_in_echo_config = True
    for cost_config_dict in config.EchoLockConfig.values():
        echo_cost_list = cost_config_dict.get(this_echo_cost_key, [])
        this_echo_cost_not_in_echo_config &= (len(echo_cost_list) == 0)

    if this_echo_cost_not_in_echo_config:
        if config.EchoDebugMode:
            logger(f"[Cost {this_echo_cost}]声骸都不需要，下一个", "DEBUG")
        echo_next_row(info.echoNumber)
        # 等一会，防止太快来不及挪到下一个
        time.sleep(0.3)
        return True

    # 识别声骸主词条属性
    if this_echo_cost == "4":  # 4COST描述太长，可能将副词条识别为主词条
        random_click(1510, 690)
        time.sleep(0.02)
        if (
            find_pic(
                1295,
                465,
                1360,
                515,
                f"声骸_攻击{info.adaptsResolution}.png",
                0.7,
                need_resize=False,
            )
            is None
        ):
            for i in range(18):
                control.scroll(1, 1510 * width_ratio, 690 * height_ratio)
                time.sleep(0.02)
            time.sleep(0.8)
            random_click(1510, 690)
    region = set_region(1425, 425, 1620, 470)
    cost_mapping = {
        "1": (echo.echoCost1MainStatus, 1),
        "3": (echo.echoCost3MainStatus, 1),
        "4": (echo.echoCost4MainStatus, 1),
    }
    func, param = cost_mapping[this_echo_cost]
    text_result = wait_text_designated_area(func, param, region, 3)
    if is_echo_ebug:
        print(
            "\n wait_text_designated_area(0)" + str(text_result)
        )  # 主词条识别失败Debug使用
    this_echo_main_status = wait_text_result_search(text_result)
    if is_echo_ebug:
        print(
            "\n wait_text_result_search(text_result)(1)" + str(this_echo_main_status)
        )  # 主词条识别失败Debug使用
    if this_echo_main_status is False:
        # 增加对衍射伤害及湮灭伤害的识别容错
        text_result = wait_text_designated_area(
            {"灭伤害加成", "射伤害加成"}, 1, region, 3
        )
        if is_echo_ebug:
            print(
                "\n wait_text_designated_area(2)" + str(text_result)
            )  # 主词条识别失败Debug使用
        if text_result.text == "灭伤害加成":
            this_echo_main_status = "湮灭伤害加成"
        elif text_result.text == "行射伤害加成":
            this_echo_main_status = "衍射伤害加成"
        # elif text_result.text == "...":
        #     this_echo_main_status = "..."
    if is_echo_ebug:
        print(
            "\n this_echo_main_status(3)" + str(this_echo_main_status)
        )  # 主词条识别失败Debug使用
    this_echo_main_status = remove_non_chinese(this_echo_main_status)
    if config.EchoDebugMode:
        logger(f"当前声骸主词条为：{this_echo_main_status}", "DEBUG")
    if this_echo_main_status is None or this_echo_main_status is False:
        logger(f"声骸主词条识别错误", "ERROR")
        return False

    # 每个套装都不需要这个cost对应的主属性，直接跳过，不检测套装属性
    echo_main_is_not_exist_in_all_set = True
    # 每个套装都需要这个cost对应的主属性，直接锁定，不检测套装属性
    echo_main_is_exist_in_all_set = True
    for cost_config_dict in config.EchoLockConfig.values():
        echo_main_is_not_exist_in_all_set &= (
            this_echo_main_status not in cost_config_dict.get(this_echo_cost_key, [])
        )
        echo_main_is_exist_in_all_set &= this_echo_main_status in cost_config_dict.get(
            this_echo_cost_key, []
        )
    if echo_main_is_not_exist_in_all_set:
        if config.EchoDebugMode:
            logger(f"主属性[{str(this_echo_main_status)}]都不需要，下一个", "DEBUG")
        echo_next_row(info.echoNumber)
        return True
    if echo_main_is_exist_in_all_set:
        if config.EchoDebugMode:
            logger(f"主属性[{str(this_echo_main_status)}]都需要，直接锁定", "DEBUG")
        info.inSpecEchoQuantity += 1
        click_position(coordinate_unlock)
        time.sleep(0.5)
        echo_next_row(info.echoNumber)
        return True

    # 识别声骸套装属性
    region = set_region(1295, 430, 1850, 930)
    text_result = wait_text_designated_area(echo.echoSetName, 2, region, 5)
    this_echo_set = wait_text_result_search(text_result)
    this_echo_set = remove_non_chinese(this_echo_set)
    if this_echo_set:
        if config.EchoDebugMode:
            logger(f"当前声骸为套装为：{this_echo_set}", "DEBUG")
        pass
    else:
        random_click(1510, 690)
        time.sleep(0.02)
        for i in range(18):
            control.scroll(-1, 1510 * width_ratio, 690 * height_ratio)
            time.sleep(0.02)
        time.sleep(0.8)
        random_click(1510, 690)
        text_result = wait_text_designated_area(echo.echoSetName, 2, region, 5)
        this_echo_set = wait_text_result_search(text_result)
        this_echo_set = remove_non_chinese(this_echo_set)
        if this_echo_set:
            if config.EchoDebugMode:
                logger(f"当前声骸为套装为：{this_echo_set}", "DEBUG")

        # 上滚恢复到主词条页面
        random_click(1510, 690)
        time.sleep(0.02)
        for i in range(18):
            control.scroll(1, 1510 * width_ratio, 690 * height_ratio)
            time.sleep(0.02)
        time.sleep(0.8)
        random_click(1510, 690)

        if not this_echo_set:
            logger(f"声骸套装识别错误", "ERROR")
            return False

    # 声骸信息合成
    log_str = (
        ""
        + f"当前是第{info.echoNumber}个声骸"
        + f"，{this_echo_cost}Cost"
        + f"，{this_echo_set}"
        + f"，{this_echo_main_status}"
    )
    # 锁定声骸，输出声骸信息
    if is_echo_main_status_valid(
        this_echo_set, this_echo_cost_key, this_echo_main_status, config.EchoLockConfig
    ):
        if this_echo_lock is True:
            if config.EchoDebugMode:
                logger("当前声骸符合要求，已处于锁定状态", "DEBUG")
                # 此处无作用，因为锁定的直接跳过了，提高效率
                log_str = log_str + "，已锁定"
                logger(log_str, "DEBUG")
        else:
            if config.EchoDebugMode:
                logger(f"当前声骸符合要求，锁定声骸", "DEBUG")
            log_str = log_str + "，执行锁定"
            info.inSpecEchoQuantity += 1
            # random_click(1807, 327)
            click_position(coordinate_unlock)
            time.sleep(0.5)
            logger(log_str)
    else:
        if config.EchoDebugMode:
            logger(f"不符合，跳过", "DEBUG")
    # echo_next_row(this_echo_row)
    echo_next_row(info.echoNumber)
