### ISSUE TITLE
运行报错报错

### ISSUE THREAD

**Issue by 18664249165** [lazydog28/mc_auto_boss#34]
PS C:\WINDOWS\system32> cd C:\mc_auto_boss-master
PS C:\mc_auto_boss-master> python background/main.py
Traceback (most recent call last):
  File "C:\mc_auto_boss-master\background\main.py", line 11, in <module>
    from task import task as boss_task
  File "C:\mc_auto_boss-master\background\task\__init__.py", line 9, in <module>
    from .pages.general import pages as general_pages
  File "C:\mc_auto_boss-master\background\task\pages\__init__.py", line 13, in <module>
    from utils import *
  File "C:\mc_auto_boss-master\background\utils.py", line 17, in <module>
    from ocr import ocr
  File "C:\mc_auto_boss-master\background\ocr.py", line 8, in <module>
    from ppocronnx import TextSystem
  File "C:\mc_auto_boss-master\background\ppocronnx\__init__.py", line 1, in <module>
    from .predict_system import TextSystem, TextClassifier, TextRecognizer, TextDetector
  File "C:\mc_auto_boss-master\background\ppocronnx\predict_system.py", line 21, in <module>
    from .cls import TextClassifier
  File "C:\mc_auto_boss-master\background\ppocronnx\cls\__init__.py", line 1, in <module>
    from .predict_cls import TextClassifier
  File "C:\mc_auto_boss-master\background\ppocronnx\cls\predict_cls.py", line 21, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'
PS C:\mc_auto_boss-master>

**Comment by Panyongying** [comment]
重新安装依赖啊

**Comment by GeiNiMaYiQuan** [comment]
pip install onnxruntime
