### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Chinzicam** [lazydog28/mc_auto_boss#54]
```bash
2024-06-08 16:12:45 战斗次数：0 吸收次数：0 初始化完成
2024-06-08 16:12:45 战斗次数：0 吸收次数：0 鼠标重置进程启动成功
2024-06-08 16:12:51 战斗次数：0 吸收次数：0 启动BOSS脚本
2024-06-08 16:12:51 战斗次数：0 吸收次数：0 初始化中
2024-06-08 16:12:51 战斗次数：0 吸收次数：0 窗口大小：1024x576 当前屏幕缩放：1.25 游戏分辨率：1280x720
2024-06-08 16:12:51 战斗次数：0 吸收次数：0 项目路径：C:\Users\czc\Desktop\pydemo\mc_auto_boss
2024-06-08 16:12:51 战斗次数：0 吸收次数：0 将窗口移动至左上角2024-06-08 16:13:02.1377850 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\ITtools\Python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-06-08 16:13:02.1442196 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:870 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.

2024-06-08 16:13:02 战斗次数：0 吸收次数：0 初始化完成
2024-06-08 16:13:02 战斗次数：0 吸收次数：0 任务进程开始运行
2024-06-08 16:13:02 战斗次数：0 吸收次数：0 请将鼠标移出游戏窗口，避免干扰脚本运行Process task:
Traceback (most recent call last):
  File "E:\ITtools\Python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "E:\ITtools\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\czc\Desktop\pydemo\mc_auto_boss\background\main.py", line 31, in run
    result = ocr(img)
  File "C:\Users\czc\Desktop\pydemo\mc_auto_boss\background\ocr.py", line 32, in ocr
    results = ocrIns.ocr(img)[0]
  File "E:\ITtools\Python\lib\site-packages\paddleocr\paddleocr.py", line 668, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "E:\ITtools\Python\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "E:\ITtools\Python\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 244, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "E:\ITtools\Python\lib\site-packages\paddle\inference\wrapper.py", line 52, in tensor_copy_from_cpu
    self._copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)
```
- pip install安装没任何问题，走一键启动也没问题，就是一跑main.py就报错。本地是有onnxruntime_providers_cuda.dll文件的，尝试过卸载重装onnxruntime库也没用

**Comment by lazydog28** [comment]
Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.


https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
