### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by cutecat1314** [lazydog28/mc_auto_boss#66]
C:\Users\16137\mc_auto_boss>python background/main.py
Traceback (most recent call last):
  File "background/main.py", line 5, in <module>
    import init
  File "C:\Users\16137\mc_auto_boss\background\init.py", line 10, in <module>
    from status import logger
  File "C:\Users\16137\mc_auto_boss\background\status.py", line 11, in <module>
    from config import config
  File "C:\Users\16137\mc_auto_boss\background\config.py", line 14, in <module>
    class Config(BaseModel):
  File "C:\Users\16137\mc_auto_boss\background\config.py", line 17, in Config
    TargetBoss: list[str] = Field(
TypeError: 'type' object is not subscriptable

**Comment by lazydog28** [comment]
你使用的python版本是多少？

**Comment by cutecat1314** [comment]
3.8

**Comment by lazydog28** [comment]
使用python3.10
